import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

export function generateRenewalPDF(businessProfile, licenseType, formData) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header background
  doc.setFillColor(13, 27, 42);
  doc.rect(0, 0, pageW, 40, 'F');

  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('ComplianceAI', 15, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Business License Renewal Form', 15, 28);
  doc.setTextColor(26, 86, 219);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(licenseType.replace(/_/g, ' '), pageW - 15, 22, { align: 'right' });

  y = 55;

  // Business Details section
  doc.setTextColor(13, 27, 42);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Business Details', 15, y);
  y += 6;
  doc.setDrawColor(26, 86, 219);
  doc.setLineWidth(0.5);
  doc.line(15, y, pageW - 15, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);

  const bizFields = [
    ['Business Name', businessProfile?.business_name || ''],
    ['Owner Name', businessProfile?.owner_name || ''],
    ['Address', businessProfile?.address || ''],
    ['City / State', `${businessProfile?.city || ''}, ${businessProfile?.state || ''}`],
    ['Phone', businessProfile?.phone || ''],
    ['Email', businessProfile?.email || ''],
    ['GSTIN', businessProfile?.gstin || 'Not provided'],
  ];

  for (const [label, value] of bizFields) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(107, 114, 128);
    doc.text(label + ':', 15, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(17, 24, 39);
    doc.text(value, 70, y);
    y += 7;
  }

  y += 6;

  // Form Fields section
  if (formData?.formFields?.length) {
    doc.setTextColor(13, 27, 42);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Pre-filled Form Fields', 15, y);
    y += 6;
    doc.setDrawColor(26, 86, 219);
    doc.line(15, y, pageW - 15, y);
    y += 8;
    doc.setFontSize(10);

    for (const field of formData.formFields) {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(107, 114, 128);
      doc.text(field.fieldName + ':', 15, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(17, 24, 39);
      const val = String(field.fieldValue || '');
      const lines = doc.splitTextToSize(val, pageW - 85);
      doc.text(lines, 80, y);
      y += Math.max(7, lines.length * 5);
    }
    y += 4;
  }

  // Document Checklist
  if (formData?.documentChecklist?.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setTextColor(13, 27, 42);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Document Checklist', 15, y);
    y += 6;
    doc.setDrawColor(26, 86, 219);
    doc.line(15, y, pageW - 15, y);
    y += 8;
    doc.setFontSize(10);

    for (const item of formData.documentChecklist) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setDrawColor(200, 200, 200);
      doc.rect(15, y - 4, 5, 5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(55, 65, 81);
      doc.text(item, 24, y);
      y += 7;
    }
    y += 4;
  }

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 285, pageW, 12, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text(`Generated by ComplianceAI on ${format(new Date(), 'dd MMM yyyy')} • Page ${i} of ${totalPages}`, pageW / 2, 292, { align: 'center' });
  }

  const blob = doc.output('blob');
  return URL.createObjectURL(blob);
}
